### ISSUE TITLE
No support for NodePort service configuration

### ISSUE THREAD

**Issue by otisaardvark** [hugoprudente/charts#39]
The `service.yaml` template does not support a NodePort service configuration 

The following code added to the template after `spec:` would enable this service configuration

```
...
{{- if eq .Values.service.serviceType "NodePort" }}
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol:  {{ .Values.service.protocol }}
{{- else if (or (eq .Values.service.serviceType "ClusterIP") (empty .Values.service.serviceType)) }}
...
```

To use use this configuration, the `values.yaml` would need to contain a definition similar to the following: -

```
service:
  serviceType: NodePort
  port: 30000
  nodePort: 30000
  protocol: TCP
  labels: {}
  annotations: {}
```
